sudo: false
language: perl
rvm:
  - 2.3
perl:
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
  - "5.8"
before_install:
  - cpanm Proc::Guard # for xt/
  - gem install fluentd --no-document

